name: Actualizar Fondos Diariamente

on:
  schedule:
    - cron: "30 7 * * 1-5"
  workflow_dispatch:

jobs:
  actualizar-y-enviar:
    runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Actualizar fondos y enviar email
        env:
          EMAIL_REMITENTE: ${{ secrets.EMAIL_REMITENTE }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}
        run: python actualizar_fondos.py

      - name: Guardar Excel actualizado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Excel actualizado automaticamente"
          file_pattern: "fondos_inversion.xlsx"
